spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3310/sharding_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
